from dotenv import load_dotenv
import os

ENV = os.getenv("ENV")

if ENV == "PROD":
    load_dotenv(dotenv_path=".env.prod")
else:
    load_dotenv(dotenv_path=".env.dev")

ZULIP_EMAIL=os.getenv("ZULIP_EMAIL")
ZULIP_API_KEY=os.getenv("ZULIP_API_KEY")
ZULIP_BASE_URL=os.getenv("ZULIP_BASE_URL")

STREAM_NAME=os.getenv("STREAM_NAME")

GITLAB_BASE_URL=os.getenv("GITLAB_BASE_URL")
GITLAB_BASE_DOMAIN=os.getenv("GITLAB_BASE_DOMAIN")
GITLAB_MR_GENERATOR_TRIGGER_TOKEN=os.getenv("GITLAB_MR_GENERATOR_TRIGGER_TOKEN")
GITLAB_MR_GENERATOR_PROJECT_PATH=os.getenv("GITLAB_MR_GENERATOR_PROJECT_PATH")
GITLAB_API_V4_URL=os.getenv("GITLAB_API_V4_URL")
GITLAB_API_TOKEN=os.getenv("GITLAB_API_TOKEN")
GITLAB_BRANCH=os.getenv("GITLAB_BRANCH")
GITLAB_CD_GROUP_ID=os.getenv("GITLAB_CD_GROUP_ID")

HARBOR_BASE_URL=os.getenv("HARBOR_BASE_URL")
HARBOR_USERNAME=os.getenv("HARBOR_USERNAME")
HARBOR_PASSWORD=os.getenv("HARBOR_PASSWORD")
HARBOR_PROJECT=os.getenv("HARBOR_PROJECT")

GITLAB_REPLICATE_PACKAGE_TRIGGER_TOKEN=os.getenv("GITLAB_REPLICATE_PACKAGE_TRIGGER_TOKEN")
GITLAB_REPLICATE_PACKAGE_PROJECT_PATH=os.getenv("GITLAB_REPLICATE_PACKAGE_PROJECT_PATH")
GITLAB_REPLICATE_PACKAGE_API_TOKEN=os.getenv("GITLAB_REPLICATE_PACKAGE_API_TOKEN")
