version: '3.8'

services:
  zulip-bot:
    build:
      context: .
      dockerfile: Dockerfile-airgapped
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=PROD
    volumes:
      - .:/app
    command:
      - python
      - main.py